version: '2'

services:
  api:
    restart: always
    build: ./api
    expose:
      - "8000"
    volumes:
      - /usr/src/app/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    depends_on:
      - mongodb

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - api
      - frontend
    depends_on:
      - api
      - frontend

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=dev
    ports:
      - "8080:8080"

  mongodb:
    restart: always
    build: ./mongodb
