version: '3.3'

services:
  api:
    restart: always
    build: ./api
    volumes:
      - /usr/src/app/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :5000 run:app
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=${APP_ENV}

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - /www/static
    depends_on:
      - api
      - frontend

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=${APP_ENV}

  mongodb:
    restart: always
    build: ./mongodb
    ports:
      - "27017:27017"
